-- MySQL Script generated by MySQL Workbench
-- Sat Feb  2 12:52:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbzivi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbzivi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbzivi` DEFAULT CHARACTER SET utf8 ;
USE `dbzivi` ;

-- -----------------------------------------------------
-- Table `dbzivi`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbzivi`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `dbzivi`.`Cliente` (
  `nome` VARCHAR(255) NOT NULL,
  `idade` INT NULL,
  `endereco` VARCHAR(255) NULL,
  `id_conta` INT NOT NULL,
  PRIMARY KEY (`nome`, `id_conta`),
  UNIQUE INDEX `n_conta_UNIQUE` (`id_conta` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbzivi`.`Conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbzivi`.`Conta` ;

CREATE TABLE IF NOT EXISTS `dbzivi`.`Conta` (
  `id_conta` INT NOT NULL,
  `saldo` FLOAT NULL,
  PRIMARY KEY (`id_conta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbzivi`.`Transacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbzivi`.`Transacao` ;

CREATE TABLE IF NOT EXISTS `dbzivi`.`Transacao` (
  `idTransacao` VARCHAR(255) NOT NULL,
  `id_conta` INT UNSIGNED NULL,
  `valor` FLOAT NULL,
  PRIMARY KEY (`idTransacao`),
  UNIQUE INDEX `idTransacao_UNIQUE` (`idTransacao` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
